"""esquema sprint 1 consolidado

Revision ID: 75aa6ae191e4
Revises:
Create Date: 2026-09-14 15:02:04.932043

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "75aa6ae191e4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


MODULOS = (
    ("EMPRESAS", "Mi empresa", "Datos y configuracion de empresa", "building", 10, True),
    ("USUARIOS", "Usuarios", "Altas, bajas y accesos", "users", 20, True),
    ("ROLES", "Roles y permisos", "Gestion de autorizaciones", "shield", 30, True),
    ("BITACORA", "Bitacora", "Auditoria del sistema", "history", 40, True),
    ("ORGANIZACION", "Organizacion", "Departamentos y cargos", "sitemap", 50, False),
    ("RECLUTAMIENTO", "Reclutamiento", "Vacantes y postulaciones", "briefcase", 60, False),
)

PERMISOS = (
    "empresa:ver",
    "empresa:editar",
    "usuarios:ver",
    "usuarios:crear",
    "usuarios:editar",
    "usuarios:eliminar",
    "usuarios:restaurar",
    "usuarios:desbloquear",
    "usuarios:cambiar_password",
    "roles:gestionar",
    "bitacora:ver",
    "departamentos:ver",
    "departamentos:crear",
    "departamentos:editar",
    "departamentos:eliminar",
    "cargos:ver",
    "cargos:crear",
    "cargos:editar",
    "cargos:eliminar",
    "vacantes:ver",
    "vacantes:crear",
    "vacantes:editar",
    "vacantes:publicar",
    "vacantes:eliminar",
    "habilidades:ver",
    "habilidades:gestionar",
    "postulantes:ver",
    "postulantes:gestionar",
    "postulaciones:ver",
    "postulaciones:gestionar",
    "platform:empresas:ver",
    "platform:empresas:crear",
    "platform:empresas:editar",
    "platform:empresas:suspender",
    "platform:empresas:eliminar",
    "platform:empresas:restaurar",
    "platform:bitacora:ver",
    "platform:usuarios:gestionar",
    "platform:organizacion:gestionar",
    "platform:vacantes:gestionar",
    "platform:habilidades:gestionar",
    "platform:postulantes:ver",
    "platform:postulaciones:ver",
    "platform:postulaciones:gestionar",
    "platform:modulos:ver",
    "platform:modulos:gestionar",
)


def _datos_permiso(codigo: str) -> tuple[str, str, str]:
    partes = codigo.split(":")
    if partes[0] == "platform":
        return "PLATFORM", partes[1], partes[2]
    recurso, operacion = partes
    if recurso in {"departamentos", "cargos"}:
        modulo = "ORGANIZACION"
    elif recurso in {"vacantes", "habilidades", "postulantes", "postulaciones"}:
        modulo = "RECLUTAMIENTO"
    else:
        modulo = {
            "empresa": "EMPRESAS",
            "usuarios": "USUARIOS",
            "roles": "ROLES",
            "bitacora": "BITACORA",
        }[recurso]
    return modulo, recurso, operacion


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "empresa",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("nit", sa.String(length=30), nullable=True),
        sa.Column("razon_social", sa.String(length=200), nullable=False),
        sa.Column("nombre_comercial", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=True),
        sa.Column("telefono", sa.String(length=40), nullable=True),
        sa.Column("direccion", sa.Text(), nullable=True),
        sa.Column("ciudad", sa.String(length=100), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("color_primario", sa.String(length=20), server_default="#2563eb", nullable=False),
        sa.Column("portal_publico_activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("eliminado_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("eliminado_por_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "fecha_registro",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(slug)) > 0", name="chk_empresa_slug_no_vacio"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nit"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("idx_empresa_eliminado_at", "empresa", ["eliminado_at"], unique=False)
    op.create_index(
        "uq_empresa_slug_ci", "empresa", [sa.literal_column("lower(slug)")], unique=True
    )
    op.create_table(
        "modulo",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("codigo", sa.String(length=60), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("icono", sa.String(length=60), nullable=True),
        sa.Column("orden", sa.Integer(), server_default="100", nullable=False),
        sa.Column("es_core", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "parametro_legal",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("codigo", sa.String(length=80), nullable=False),
        sa.Column("nombre", sa.String(length=160), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("tipo_valor", sa.String(length=30), nullable=False),
        sa.Column("pais", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "permiso",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("codigo", sa.String(length=120), nullable=False),
        sa.Column("modulo", sa.String(length=80), nullable=False),
        sa.Column("recurso", sa.String(length=80), nullable=False),
        sa.Column("operacion", sa.String(length=80), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
        sa.UniqueConstraint(
            "modulo", "recurso", "operacion", name="uq_permiso_modulo_recurso_operacion"
        ),
    )
    op.create_table(
        "plan_suscripcion",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("precio_mensual", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("max_empleados", sa.Integer(), nullable=False),
        sa.Column(
            "modulos", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "empresa_modulo",
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("modulo_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("habilitado", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("fecha_habilitacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("habilitado_por_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["modulo_id"], ["modulo.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("empresa_id", "modulo_id"),
    )
    op.create_index("idx_empresa_modulo_empresa_id", "empresa_modulo", ["empresa_id"], unique=False)
    op.create_table(
        "etapa_reclutamiento",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=30), nullable=True),
        sa.Column("es_inicial", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("es_contratado", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("es_rechazado", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("orden > 0", name="ck_etapa_reclutamiento_orden_positivo"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "nombre", name="uq_etapa_reclutamiento_empresa_nombre"),
        sa.UniqueConstraint("empresa_id", "orden", name="uq_etapa_reclutamiento_empresa_orden"),
    )
    op.create_index(
        "idx_etapa_reclutamiento_empresa_id", "etapa_reclutamiento", ["empresa_id"], unique=False
    )
    op.create_table(
        "habilidad",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("categoria", sa.String(length=120), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "nombre", name="uq_habilidad_empresa_nombre"),
    )
    op.create_index("idx_habilidad_empresa_id", "habilidad", ["empresa_id"], unique=False)
    op.create_index(
        "uq_habilidad_empresa_nombre_ci",
        "habilidad",
        ["empresa_id", sa.literal_column("lower(nombre)")],
        unique=True,
    )
    op.create_table(
        "motivo_rechazo",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "nombre", name="uq_motivo_rechazo_empresa_nombre"),
    )
    op.create_index("idx_motivo_rechazo_empresa_id", "motivo_rechazo", ["empresa_id"], unique=False)
    op.create_table(
        "parametro_valor",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("parametro_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("valor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("vigente_desde", sa.Date(), nullable=False),
        sa.Column("vigente_hasta", sa.Date(), nullable=False),
        sa.Column("norma_legal", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parametro_id"], ["parametro_legal.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_parametro_valor_parametro_vigencia",
        "parametro_valor",
        ["parametro_id", "vigente_desde"],
        unique=False,
    )
    op.create_table(
        "postulante",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("nombres", sa.String(length=120), nullable=False),
        sa.Column("apellidos", sa.String(length=120), nullable=False),
        sa.Column("ci", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("telefono", sa.String(length=40), nullable=False),
        sa.Column("direccion", sa.Text(), nullable=True),
        sa.Column("ciudad", sa.String(length=100), nullable=False),
        sa.Column("fecha_nacimiento", sa.Date(), nullable=True),
        sa.Column("cv_url", sa.Text(), nullable=True),
        sa.Column("cv_texto", sa.Text(), nullable=True),
        sa.Column("linkedin", sa.Text(), nullable=True),
        sa.Column("nivel_educativo", sa.String(length=20), nullable=False),
        sa.Column("anios_experiencia", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fuente", sa.String(length=20), nullable=False),
        sa.Column("en_banco_talento", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "fecha_registro",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fuente IN ('PORTAL_WEB', 'APP_MOVIL', 'LINKEDIN', 'REFERIDO', 'FERIA', 'OTRO')",
            name="ck_postulante_fuente",
        ),
        sa.CheckConstraint(
            "nivel_educativo IN ('SECUNDARIA', 'TECNICO', 'LICENCIATURA', 'MAESTRIA', 'DOCTORADO')",
            name="ck_postulante_nivel_educativo",
        ),
        sa.CheckConstraint("anios_experiencia >= 0", name="ck_postulante_experiencia_no_negativa"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "ci", name="uq_postulante_empresa_ci"),
    )
    op.create_index("idx_postulante_email", "postulante", ["email"], unique=False)
    op.create_index("idx_postulante_empresa_id", "postulante", ["empresa_id"], unique=False)
    op.create_index(
        "uq_postulante_empresa_ci_ci",
        "postulante",
        ["empresa_id", sa.literal_column("lower(ci)")],
        unique=True,
    )
    op.create_table(
        "rol",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("codigo", sa.String(length=80), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("es_sistema", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "codigo", name="uq_rol_empresa_codigo"),
        sa.UniqueConstraint("empresa_id", "nombre", name="uq_rol_empresa_nombre"),
    )
    op.create_index("idx_rol_empresa_id", "rol", ["empresa_id"], unique=False)
    op.create_index(
        "uq_rol_empresa_codigo_ci",
        "rol",
        ["empresa_id", sa.literal_column("lower(codigo)")],
        unique=True,
    )
    op.create_index(
        "uq_rol_empresa_nombre_ci",
        "rol",
        ["empresa_id", sa.literal_column("lower(nombre)")],
        unique=True,
    )
    op.create_index(
        "uq_rol_global_codigo_ci",
        "rol",
        [sa.literal_column("lower(codigo)")],
        unique=True,
        postgresql_where=sa.text("empresa_id IS NULL"),
    )
    op.create_index(
        "uq_rol_global_nombre_ci",
        "rol",
        [sa.literal_column("lower(nombre)")],
        unique=True,
        postgresql_where=sa.text("empresa_id IS NULL"),
    )
    op.create_table(
        "suscripcion",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("plan_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "fecha_inicio", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False
        ),
        sa.Column("fecha_fin", sa.Date(), nullable=True),
        sa.Column("estado", sa.String(length=30), server_default="ACTIVA", nullable=False),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_id"], ["plan_suscripcion.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuario",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("nombres", sa.String(length=120), nullable=False),
        sa.Column("apellidos", sa.String(length=120), server_default="", nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("telefono", sa.String(length=40), nullable=True),
        sa.Column("ultimo_acceso", sa.DateTime(timezone=True), nullable=True),
        sa.Column("debe_cambiar_password", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("intentos_fallidos", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bloqueado_hasta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_intento_fallido", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("email_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("eliminado_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("eliminado_por_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "intentos_fallidos >= 0", name="ck_usuario_intentos_fallidos_no_negativo"
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "email", name="uq_usuario_empresa_email"),
        sa.UniqueConstraint("empresa_id", "username", name="uq_usuario_empresa_username"),
    )
    op.create_index("idx_usuario_bloqueado_hasta", "usuario", ["bloqueado_hasta"], unique=False)
    op.create_index("idx_usuario_eliminado_at", "usuario", ["eliminado_at"], unique=False)
    op.create_index("idx_usuario_email", "usuario", ["email"], unique=False)
    op.create_index("idx_usuario_empresa_id", "usuario", ["empresa_id"], unique=False)
    op.create_index(
        "uq_usuario_empresa_email_ci",
        "usuario",
        ["empresa_id", sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_index(
        "uq_usuario_empresa_username_ci",
        "usuario",
        ["empresa_id", sa.literal_column("lower(username)")],
        unique=True,
    )
    op.create_index(
        "uq_usuario_plataforma_email_ci",
        "usuario",
        [sa.literal_column("lower(email)")],
        unique=True,
        postgresql_where=sa.text("empresa_id IS NULL"),
    )
    op.create_index(
        "uq_usuario_plataforma_username_ci",
        "usuario",
        [sa.literal_column("lower(username)")],
        unique=True,
        postgresql_where=sa.text("empresa_id IS NULL"),
    )
    op.create_table(
        "bitacora",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("usuario_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("actor_etiqueta", sa.String(length=150), nullable=True),
        sa.Column("modulo", sa.String(length=80), nullable=False),
        sa.Column("accion", sa.String(length=100), nullable=False),
        sa.Column("nivel", sa.String(length=16), server_default="INFO", nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("tabla_afectada", sa.String(length=100), nullable=True),
        sa.Column("registro_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("datos_previos", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("datos_nuevos", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_origen", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "fecha", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_bitacora_accion", "bitacora", ["accion"], unique=False)
    op.create_index("idx_bitacora_empresa_id", "bitacora", ["empresa_id"], unique=False)
    op.create_index("idx_bitacora_fecha", "bitacora", ["fecha"], unique=False)
    op.create_index("idx_bitacora_modulo", "bitacora", ["modulo"], unique=False)
    op.create_index("idx_bitacora_usuario_id", "bitacora", ["usuario_id"], unique=False)
    op.create_table(
        "departamento",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("codigo", sa.String(length=40), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("departamento_padre_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("responsable_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["departamento_padre_id"], ["departamento.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["responsable_id"], ["usuario.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "nombre", name="uq_departamento_empresa_nombre"),
    )
    op.create_index("idx_departamento_empresa_id", "departamento", ["empresa_id"], unique=False)
    op.create_index(
        "idx_departamento_padre_id", "departamento", ["departamento_padre_id"], unique=False
    )
    op.create_index(
        "idx_departamento_responsable_id", "departamento", ["responsable_id"], unique=False
    )
    op.create_index(
        "uq_departamento_empresa_nombre_ci",
        "departamento",
        ["empresa_id", sa.literal_column("lower(nombre)")],
        unique=True,
    )
    op.create_table(
        "email_verification_token",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("usuario_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "idx_email_verification_token_expires_at",
        "email_verification_token",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "idx_email_verification_token_usuario_id",
        "email_verification_token",
        ["usuario_id"],
        unique=False,
    )
    op.create_table(
        "password_reset_token",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("usuario_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_password_reset_token_empresa_id", "password_reset_token", ["empresa_id"], unique=False
    )
    op.create_index(
        "idx_password_reset_token_expires_at", "password_reset_token", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_password_reset_token_usuario_id", "password_reset_token", ["usuario_id"], unique=False
    )
    op.create_table(
        "refresh_token",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("usuario_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_refresh_token_empresa_id", "refresh_token", ["empresa_id"], unique=False)
    op.create_index("idx_refresh_token_expires_at", "refresh_token", ["expires_at"], unique=False)
    op.create_index("idx_refresh_token_usuario_id", "refresh_token", ["usuario_id"], unique=False)
    op.create_table(
        "rol_permiso",
        sa.Column("rol_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("permiso_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["permiso_id"], ["permiso.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rol_id"], ["rol.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rol_id", "permiso_id"),
    )
    op.create_index("idx_rol_permiso_permiso_id", "rol_permiso", ["permiso_id"], unique=False)
    op.create_index("idx_rol_permiso_rol_id", "rol_permiso", ["rol_id"], unique=False)
    op.create_table(
        "usuario_rol",
        sa.Column("usuario_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("rol_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("asignado_por_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "fecha_asignacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asignado_por_id"], ["usuario.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rol_id"], ["rol.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("usuario_id", "rol_id"),
    )
    op.create_index("idx_usuario_rol_rol_id", "usuario_rol", ["rol_id"], unique=False)
    op.create_index("idx_usuario_rol_usuario_id", "usuario_rol", ["usuario_id"], unique=False)
    op.create_table(
        "cargo",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("departamento_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("codigo", sa.String(length=40), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("nivel", sa.String(length=80), nullable=True),
        sa.Column("salario_min", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salario_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "salario_max IS NULL OR salario_max >= 0", name="ck_cargo_salario_max_no_negativo"
        ),
        sa.CheckConstraint(
            "salario_min IS NULL OR salario_max IS NULL OR salario_max >= salario_min",
            name="ck_cargo_rango_salario",
        ),
        sa.CheckConstraint(
            "salario_min IS NULL OR salario_min >= 0", name="ck_cargo_salario_min_no_negativo"
        ),
        sa.ForeignKeyConstraint(["departamento_id"], ["departamento.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "nombre", name="uq_cargo_empresa_nombre"),
    )
    op.create_index("idx_cargo_departamento_id", "cargo", ["departamento_id"], unique=False)
    op.create_index("idx_cargo_empresa_id", "cargo", ["empresa_id"], unique=False)
    op.create_index(
        "uq_cargo_empresa_nombre_ci",
        "cargo",
        ["empresa_id", sa.literal_column("lower(nombre)")],
        unique=True,
    )
    op.create_table(
        "vacante",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("cargo_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("departamento_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("responsable_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("titulo", sa.String(length=180), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("requisitos", sa.Text(), nullable=True),
        sa.Column("beneficios", sa.Text(), nullable=True),
        sa.Column("cantidad_vacantes", sa.Integer(), server_default="1", nullable=False),
        sa.Column("salario_min", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salario_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("mostrar_salario", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("modalidad", sa.String(length=20), nullable=False),
        sa.Column("ubicacion", sa.String(length=160), nullable=True),
        sa.Column("experiencia_min", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fecha_publicacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fecha_cierre", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estado", sa.String(length=20), server_default="BORRADOR", nullable=False),
        sa.Column(
            "fecha_registro",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado IN ('BORRADOR', 'PUBLICADA', 'PAUSADA', 'CERRADA', 'CANCELADA')",
            name="ck_vacante_estado",
        ),
        sa.CheckConstraint(
            "modalidad IN ('PRESENCIAL', 'REMOTO', 'HIBRIDO')", name="ck_vacante_modalidad"
        ),
        sa.CheckConstraint("cantidad_vacantes > 0", name="ck_vacante_cantidad_positiva"),
        sa.CheckConstraint("experiencia_min >= 0", name="ck_vacante_experiencia_no_negativa"),
        sa.CheckConstraint(
            "fecha_cierre IS NULL OR fecha_publicacion IS NULL OR fecha_cierre >= fecha_publicacion",
            name="ck_vacante_fechas",
        ),
        sa.CheckConstraint(
            "salario_max IS NULL OR salario_max >= 0", name="ck_vacante_salario_max_no_negativo"
        ),
        sa.CheckConstraint(
            "salario_min IS NULL OR salario_max IS NULL OR salario_max >= salario_min",
            name="ck_vacante_rango_salario",
        ),
        sa.CheckConstraint(
            "salario_min IS NULL OR salario_min >= 0", name="ck_vacante_salario_min_no_negativo"
        ),
        sa.ForeignKeyConstraint(["cargo_id"], ["cargo.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["departamento_id"], ["departamento.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["responsable_id"], ["usuario.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_vacante_cargo_id", "vacante", ["cargo_id"], unique=False)
    op.create_index("idx_vacante_departamento_id", "vacante", ["departamento_id"], unique=False)
    op.create_index("idx_vacante_empresa_id", "vacante", ["empresa_id"], unique=False)
    op.create_index("idx_vacante_estado", "vacante", ["estado"], unique=False)
    op.create_index("idx_vacante_fecha_cierre", "vacante", ["fecha_cierre"], unique=False)
    op.create_index("idx_vacante_responsable_id", "vacante", ["responsable_id"], unique=False)
    op.create_table(
        "postulacion",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("vacante_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("postulante_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("etapa_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("motivo_rechazo_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("empleado_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("puntaje_ia", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("puntaje_manual", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("codigo_seguimiento", sa.String(length=40), nullable=False),
        sa.Column(
            "fecha_postulacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_ultimo_cambio",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("estado", sa.String(length=20), server_default="ACTIVA", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado IN ('ACTIVA', 'RETIRADA', 'DESCARTADA', 'CONTRATADA')",
            name="ck_postulacion_estado",
        ),
        sa.CheckConstraint(
            "puntaje_ia IS NULL OR (puntaje_ia >= 0 AND puntaje_ia <= 100)",
            name="ck_postulacion_puntaje_ia",
        ),
        sa.CheckConstraint(
            "puntaje_manual IS NULL OR (puntaje_manual >= 0 AND puntaje_manual <= 100)",
            name="ck_postulacion_puntaje_manual",
        ),
        sa.ForeignKeyConstraint(["etapa_id"], ["etapa_reclutamiento.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["motivo_rechazo_id"], ["motivo_rechazo.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["postulante_id"], ["postulante.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vacante_id"], ["vacante.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_seguimiento", name="uq_postulacion_codigo_seguimiento"),
        sa.UniqueConstraint(
            "vacante_id", "postulante_id", name="uq_postulacion_vacante_postulante"
        ),
    )
    op.create_index(
        "idx_postulacion_codigo_seguimiento", "postulacion", ["codigo_seguimiento"], unique=False
    )
    op.create_index("idx_postulacion_empleado_id", "postulacion", ["empleado_id"], unique=False)
    op.create_index("idx_postulacion_estado", "postulacion", ["estado"], unique=False)
    op.create_index("idx_postulacion_etapa_id", "postulacion", ["etapa_id"], unique=False)
    op.create_index(
        "idx_postulacion_motivo_rechazo_id", "postulacion", ["motivo_rechazo_id"], unique=False
    )
    op.create_index("idx_postulacion_postulante_id", "postulacion", ["postulante_id"], unique=False)
    op.create_index("idx_postulacion_vacante_id", "postulacion", ["vacante_id"], unique=False)
    op.create_table(
        "vacante_habilidad",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("vacante_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("habilidad_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("nivel_requerido", sa.String(length=30), nullable=False),
        sa.Column("es_obligatorio", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("peso", sa.Numeric(precision=5, scale=2), server_default="1.00", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("peso > 0", name="ck_vacante_habilidad_peso_positivo"),
        sa.ForeignKeyConstraint(["habilidad_id"], ["habilidad.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vacante_id"], ["vacante.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vacante_id", "habilidad_id", name="uq_vacante_habilidad_pair"),
    )
    op.create_index(
        "idx_vacante_habilidad_habilidad_id", "vacante_habilidad", ["habilidad_id"], unique=False
    )
    op.create_table(
        "postulacion_nota",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("postulacion_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("usuario_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("contenido", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["postulacion_id"], ["postulacion.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_postulacion_nota_postulacion_id", "postulacion_nota", ["postulacion_id"], unique=False
    )
    op.create_index(
        "idx_postulacion_nota_usuario_id", "postulacion_nota", ["usuario_id"], unique=False
    )
    # ### end Alembic commands ###

    modulo = sa.table(
        "modulo",
        sa.column("codigo", sa.String),
        sa.column("nombre", sa.String),
        sa.column("descripcion", sa.String),
        sa.column("icono", sa.String),
        sa.column("orden", sa.Integer),
        sa.column("es_core", sa.Boolean),
    )
    op.bulk_insert(
        modulo,
        [
            {"codigo": c, "nombre": n, "descripcion": d, "icono": i, "orden": o, "es_core": e}
            for c, n, d, i, o, e in MODULOS
        ],
    )

    permiso = sa.table(
        "permiso",
        sa.column("codigo", sa.String),
        sa.column("modulo", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("descripcion", sa.String),
    )
    op.bulk_insert(
        permiso,
        [
            {
                "codigo": codigo,
                "modulo": _datos_permiso(codigo)[0],
                "recurso": _datos_permiso(codigo)[1],
                "operacion": _datos_permiso(codigo)[2],
                "descripcion": codigo,
            }
            for codigo in PERMISOS
        ],
    )
    op.execute(
        "INSERT INTO rol (empresa_id, codigo, nombre, descripcion, es_sistema, activo) "
        "VALUES (NULL, 'SUPER_ADMIN', 'Super Administrador', "
        "'Administrador global de SSAS', TRUE, TRUE)"
    )
    op.execute(
        "INSERT INTO rol_permiso (rol_id, permiso_id) "
        "SELECT r.id, p.id FROM rol r CROSS JOIN permiso p "
        "WHERE r.codigo = 'SUPER_ADMIN' AND r.empresa_id IS NULL "
        "AND p.codigo LIKE 'platform:%'"
    )
    op.execute(
        "INSERT INTO plan_suscripcion "
        "(nombre, precio_mensual, max_empleados, modulos, activo) VALUES "
        '(\'Basico\', 0, 25, \'["EMPRESAS", "USUARIOS", "ROLES", '
        '"BITACORA", "ORGANIZACION", "RECLUTAMIENTO"]\'::jsonb, TRUE)'
    )
    op.execute(
        "INSERT INTO parametro_legal (codigo, nombre, descripcion, tipo_valor, pais) VALUES "
        "('PARAMETROS_LABORALES_BO', 'Parametros laborales de Bolivia', "
        "'Porcentajes laborales vigentes usados por el sistema', 'JSON', 'BO')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_postulacion_nota_usuario_id", table_name="postulacion_nota")
    op.drop_index("idx_postulacion_nota_postulacion_id", table_name="postulacion_nota")
    op.drop_table("postulacion_nota")
    op.drop_index("idx_vacante_habilidad_habilidad_id", table_name="vacante_habilidad")
    op.drop_table("vacante_habilidad")
    op.drop_index("idx_postulacion_vacante_id", table_name="postulacion")
    op.drop_index("idx_postulacion_postulante_id", table_name="postulacion")
    op.drop_index("idx_postulacion_motivo_rechazo_id", table_name="postulacion")
    op.drop_index("idx_postulacion_etapa_id", table_name="postulacion")
    op.drop_index("idx_postulacion_estado", table_name="postulacion")
    op.drop_index("idx_postulacion_empleado_id", table_name="postulacion")
    op.drop_index("idx_postulacion_codigo_seguimiento", table_name="postulacion")
    op.drop_table("postulacion")
    op.drop_index("idx_vacante_responsable_id", table_name="vacante")
    op.drop_index("idx_vacante_fecha_cierre", table_name="vacante")
    op.drop_index("idx_vacante_estado", table_name="vacante")
    op.drop_index("idx_vacante_empresa_id", table_name="vacante")
    op.drop_index("idx_vacante_departamento_id", table_name="vacante")
    op.drop_index("idx_vacante_cargo_id", table_name="vacante")
    op.drop_table("vacante")
    op.drop_index("uq_cargo_empresa_nombre_ci", table_name="cargo")
    op.drop_index("idx_cargo_empresa_id", table_name="cargo")
    op.drop_index("idx_cargo_departamento_id", table_name="cargo")
    op.drop_table("cargo")
    op.drop_index("idx_usuario_rol_usuario_id", table_name="usuario_rol")
    op.drop_index("idx_usuario_rol_rol_id", table_name="usuario_rol")
    op.drop_table("usuario_rol")
    op.drop_index("idx_rol_permiso_rol_id", table_name="rol_permiso")
    op.drop_index("idx_rol_permiso_permiso_id", table_name="rol_permiso")
    op.drop_table("rol_permiso")
    op.drop_index("idx_refresh_token_usuario_id", table_name="refresh_token")
    op.drop_index("idx_refresh_token_expires_at", table_name="refresh_token")
    op.drop_index("idx_refresh_token_empresa_id", table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_index("idx_password_reset_token_usuario_id", table_name="password_reset_token")
    op.drop_index("idx_password_reset_token_expires_at", table_name="password_reset_token")
    op.drop_index("idx_password_reset_token_empresa_id", table_name="password_reset_token")
    op.drop_table("password_reset_token")
    op.drop_index("idx_email_verification_token_usuario_id", table_name="email_verification_token")
    op.drop_index("idx_email_verification_token_expires_at", table_name="email_verification_token")
    op.drop_table("email_verification_token")
    op.drop_index("uq_departamento_empresa_nombre_ci", table_name="departamento")
    op.drop_index("idx_departamento_responsable_id", table_name="departamento")
    op.drop_index("idx_departamento_padre_id", table_name="departamento")
    op.drop_index("idx_departamento_empresa_id", table_name="departamento")
    op.drop_table("departamento")
    op.drop_index("idx_bitacora_usuario_id", table_name="bitacora")
    op.drop_index("idx_bitacora_modulo", table_name="bitacora")
    op.drop_index("idx_bitacora_fecha", table_name="bitacora")
    op.drop_index("idx_bitacora_empresa_id", table_name="bitacora")
    op.drop_index("idx_bitacora_accion", table_name="bitacora")
    op.drop_table("bitacora")
    op.drop_index(
        "uq_usuario_plataforma_username_ci",
        table_name="usuario",
        postgresql_where=sa.text("empresa_id IS NULL"),
    )
    op.drop_index(
        "uq_usuario_plataforma_email_ci",
        table_name="usuario",
        postgresql_where=sa.text("empresa_id IS NULL"),
    )
    op.drop_index("uq_usuario_empresa_username_ci", table_name="usuario")
    op.drop_index("uq_usuario_empresa_email_ci", table_name="usuario")
    op.drop_index("idx_usuario_empresa_id", table_name="usuario")
    op.drop_index("idx_usuario_email", table_name="usuario")
    op.drop_index("idx_usuario_eliminado_at", table_name="usuario")
    op.drop_index("idx_usuario_bloqueado_hasta", table_name="usuario")
    op.drop_table("usuario")
    op.drop_table("suscripcion")
    op.drop_index(
        "uq_rol_global_nombre_ci", table_name="rol", postgresql_where=sa.text("empresa_id IS NULL")
    )
    op.drop_index(
        "uq_rol_global_codigo_ci", table_name="rol", postgresql_where=sa.text("empresa_id IS NULL")
    )
    op.drop_index("uq_rol_empresa_nombre_ci", table_name="rol")
    op.drop_index("uq_rol_empresa_codigo_ci", table_name="rol")
    op.drop_index("idx_rol_empresa_id", table_name="rol")
    op.drop_table("rol")
    op.drop_index("uq_postulante_empresa_ci_ci", table_name="postulante")
    op.drop_index("idx_postulante_empresa_id", table_name="postulante")
    op.drop_index("idx_postulante_email", table_name="postulante")
    op.drop_table("postulante")
    op.drop_index("idx_parametro_valor_parametro_vigencia", table_name="parametro_valor")
    op.drop_table("parametro_valor")
    op.drop_index("idx_motivo_rechazo_empresa_id", table_name="motivo_rechazo")
    op.drop_table("motivo_rechazo")
    op.drop_index("uq_habilidad_empresa_nombre_ci", table_name="habilidad")
    op.drop_index("idx_habilidad_empresa_id", table_name="habilidad")
    op.drop_table("habilidad")
    op.drop_index("idx_etapa_reclutamiento_empresa_id", table_name="etapa_reclutamiento")
    op.drop_table("etapa_reclutamiento")
    op.drop_index("idx_empresa_modulo_empresa_id", table_name="empresa_modulo")
    op.drop_table("empresa_modulo")
    op.drop_table("plan_suscripcion")
    op.drop_table("permiso")
    op.drop_table("parametro_legal")
    op.drop_table("modulo")
    op.drop_index("uq_empresa_slug_ci", table_name="empresa")
    op.drop_index("idx_empresa_eliminado_at", table_name="empresa")
    op.drop_table("empresa")
    # ### end Alembic commands ###
