"""crear postulantes y postulaciones

Revision ID: 0d142a1a7539
Revises: 7694bb109d4b
Create Date: 2026-08-30 15:56:32.942145

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0d142a1a7539'
down_revision: str | None = '7694bb109d4b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapa_postulacion',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('orden > 0', name='ck_etapa_postulacion_orden_positivo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_etapa_postulacion_codigo'),
    sa.UniqueConstraint('orden', name='uq_etapa_postulacion_orden')
    )
    op.create_table('postulante',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombres', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('ci', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('cv_url', sa.Text(), nullable=True),
    sa.Column('linkedin', sa.Text(), nullable=True),
    sa.Column('nivel_educativo', sa.String(length=20), nullable=False),
    sa.Column('anios_experiencia', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fuente', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fuente IN ('PORTAL_WEB', 'APP_MOVIL', 'LINKEDIN', 'REFERIDO', 'FERIA', 'OTRO')", name='ck_postulante_fuente'),
    sa.CheckConstraint("nivel_educativo IN ('SECUNDARIA', 'TECNICO', 'LICENCIATURA', 'MAESTRIA', 'DOCTORADO')", name='ck_postulante_nivel_educativo'),
    sa.CheckConstraint('anios_experiencia >= 0', name='ck_postulante_experiencia_no_negativa'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci', name='uq_postulante_ci')
    )
    op.create_index('idx_postulante_email', 'postulante', ['email'], unique=False)
    op.create_index('uq_postulante_ci_ci', 'postulante', [sa.literal_column('lower(ci)')], unique=True)
    op.create_table('postulacion',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vacante_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('postulante_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('etapa_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('puntaje_manual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='ACTIVA', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('ACTIVA', 'RETIRADA', 'DESCARTADA', 'CONTRATADA')", name='ck_postulacion_estado'),
    sa.CheckConstraint('puntaje_manual IS NULL OR (puntaje_manual >= 0 AND puntaje_manual <= 100)', name='ck_postulacion_puntaje_manual'),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapa_postulacion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['postulante_id'], ['postulante.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacante.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacante_id', 'postulante_id', name='uq_postulacion_vacante_postulante')
    )
    op.create_index('idx_postulacion_estado', 'postulacion', ['estado'], unique=False)
    op.create_index('idx_postulacion_etapa_id', 'postulacion', ['etapa_id'], unique=False)
    op.create_index('idx_postulacion_postulante_id', 'postulacion', ['postulante_id'], unique=False)
    op.create_index('idx_postulacion_vacante_id', 'postulacion', ['vacante_id'], unique=False)
    for tabla in ("etapa_postulacion", "postulante", "postulacion"):
        op.execute(
            f"CREATE TRIGGER trg_{tabla}_updated_at BEFORE UPDATE ON {tabla} "
            "FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()"
        )
    etapa_table = sa.table(
        "etapa_postulacion",
        sa.column("codigo", sa.String),
        sa.column("nombre", sa.String),
        sa.column("orden", sa.Integer),
    )
    op.bulk_insert(
        etapa_table,
        [
            {"codigo": "POSTULADO", "nombre": "Postulado", "orden": 1},
            {"codigo": "PRESELECCIONADO", "nombre": "Preseleccionado", "orden": 2},
            {"codigo": "ENTREVISTA", "nombre": "Entrevista", "orden": 3},
            {"codigo": "OFERTA", "nombre": "Oferta", "orden": 4},
            {"codigo": "CONTRATADO", "nombre": "Contratado", "orden": 5},
            {"codigo": "DESCARTADO", "nombre": "Descartado", "orden": 6},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_postulacion_updated_at ON postulacion")
    op.execute("DROP TRIGGER IF EXISTS trg_postulante_updated_at ON postulante")
    op.execute("DROP TRIGGER IF EXISTS trg_etapa_postulacion_updated_at ON etapa_postulacion")
    op.drop_index('idx_postulacion_vacante_id', table_name='postulacion')
    op.drop_index('idx_postulacion_postulante_id', table_name='postulacion')
    op.drop_index('idx_postulacion_etapa_id', table_name='postulacion')
    op.drop_index('idx_postulacion_estado', table_name='postulacion')
    op.drop_table('postulacion')
    op.drop_index('uq_postulante_ci_ci', table_name='postulante')
    op.drop_index('idx_postulante_email', table_name='postulante')
    op.drop_table('postulante')
    op.drop_table('etapa_postulacion')
    # ### end Alembic commands ###
