"""Esquema inicial mínimo de SSAS RRHH.

Incluye únicamente autenticación, empresas, usuarios, RBAC y bitácora. Planes,
suscripciones, parámetros legales y tablas paralelas de plataforma quedan fuera del
alcance actual.

Modelo de multitenencia:

    usuario.empresa_id  IS NULL -> administrador de la plataforma
    rol.empresa_id      IS NULL -> rol global (SUPER_ADMIN)
    bitacora.empresa_id IS NULL -> evento de la plataforma

Revision ID: 20260825_0001
Create Date: 2026-08-25
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260825_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


PERMISOS = [
    # ── Alcance empresa ──────────────────────────────────────────────────────
    (
        "empresa:ver",
        "EMPRESAS",
        "empresa",
        "ver",
        "Consultar la configuración de la propia empresa",
    ),
    (
        "empresa:editar",
        "EMPRESAS",
        "empresa",
        "editar",
        "Editar la configuración permitida de la propia empresa",
    ),
    ("usuarios:ver", "USUARIOS", "usuarios", "ver", "Consultar usuarios de la empresa"),
    ("usuarios:crear", "USUARIOS", "usuarios", "crear", "Crear usuarios de la empresa"),
    ("usuarios:editar", "USUARIOS", "usuarios", "editar", "Editar usuarios de la empresa"),
    (
        "usuarios:desbloquear",
        "USUARIOS",
        "usuarios",
        "desbloquear",
        "Desbloquear cuentas de usuario",
    ),
    (
        "usuarios:cambiar_password",
        "USUARIOS",
        "usuarios",
        "cambiar_password",
        "Asignar contraseña temporal a usuarios",
    ),
    ("roles:gestionar", "ROLES", "roles", "gestionar", "Gestionar roles y permisos"),
    ("bitacora:ver", "BITACORA", "bitacora", "ver", "Consultar la bitácora de la empresa"),
    # ── Alcance plataforma (solo roles con empresa_id NULL) ──────────────────
    ("platform:empresas:ver", "PLATFORM", "empresas", "ver", "Ver las empresas de la plataforma"),
    ("platform:empresas:crear", "PLATFORM", "empresas", "crear", "Aprovisionar una empresa nueva"),
    ("platform:empresas:editar", "PLATFORM", "empresas", "editar", "Editar datos de una empresa"),
    (
        "platform:empresas:suspender",
        "PLATFORM",
        "empresas",
        "suspender",
        "Suspender o reactivar una empresa",
    ),
    ("platform:bitacora:ver", "PLATFORM", "bitacora", "ver", "Consultar la auditoría global"),
    (
        "platform:usuarios:gestionar",
        "PLATFORM",
        "usuarios",
        "gestionar",
        "Gestionar administradores de la plataforma",
    ),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "empresa",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("nit", sa.String(length=30), nullable=True),
        sa.Column("razon_social", sa.String(length=200), nullable=False),
        sa.Column("nombre_comercial", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=True),
        sa.Column("telefono", sa.String(length=40), nullable=True),
        sa.Column("direccion", sa.Text(), nullable=True),
        sa.Column("ciudad", sa.String(length=100), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "fecha_registro",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(slug)) > 0", name="chk_empresa_slug_no_vacio"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nit", name="uq_empresa_nit"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "uq_empresa_slug_ci", "empresa", [sa.literal_column("lower(slug)")], unique=True
    )
    op.create_table(
        "permiso",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("codigo", sa.String(length=120), nullable=False),
        sa.Column("modulo", sa.String(length=80), nullable=False),
        sa.Column("recurso", sa.String(length=80), nullable=False),
        sa.Column("operacion", sa.String(length=80), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
        sa.UniqueConstraint(
            "modulo", "recurso", "operacion", name="uq_permiso_modulo_recurso_operacion"
        ),
    )
    op.create_table(
        "rol",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("codigo", sa.String(length=80), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("es_base", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "codigo", name="uq_rol_empresa_codigo"),
        sa.UniqueConstraint("empresa_id", "nombre", name="uq_rol_empresa_nombre"),
    )
    op.create_index("idx_rol_empresa_id", "rol", ["empresa_id"], unique=False)
    op.create_index(
        "uq_rol_empresa_codigo_ci",
        "rol",
        ["empresa_id", sa.literal_column("lower(codigo)")],
        unique=True,
    )
    op.create_index(
        "uq_rol_empresa_nombre_ci",
        "rol",
        ["empresa_id", sa.literal_column("lower(nombre)")],
        unique=True,
    )
    op.create_index(
        "uq_rol_global_codigo_ci",
        "rol",
        [sa.literal_column("lower(codigo)")],
        unique=True,
        postgresql_where=sa.text("empresa_id IS NULL"),
    )
    op.create_index(
        "uq_rol_global_nombre_ci",
        "rol",
        [sa.literal_column("lower(nombre)")],
        unique=True,
        postgresql_where=sa.text("empresa_id IS NULL"),
    )
    op.create_table(
        "usuario",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("apellido", sa.String(length=120), server_default="", nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("telefono", sa.String(length=40), nullable=True),
        sa.Column("ultimo_acceso", sa.DateTime(timezone=True), nullable=True),
        sa.Column("debe_cambiar_password", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("intentos_fallidos", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bloqueado_hasta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_intento_fallido", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("email_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "intentos_fallidos >= 0", name="ck_usuario_intentos_fallidos_no_negativo"
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "email", name="uq_usuario_empresa_email"),
        sa.UniqueConstraint("empresa_id", "username", name="uq_usuario_empresa_username"),
    )
    op.create_index("idx_usuario_bloqueado_hasta", "usuario", ["bloqueado_hasta"], unique=False)
    op.create_index("idx_usuario_email", "usuario", ["email"], unique=False)
    op.create_index("idx_usuario_empresa_id", "usuario", ["empresa_id"], unique=False)
    op.create_index(
        "uq_usuario_empresa_email_ci",
        "usuario",
        ["empresa_id", sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_index(
        "uq_usuario_empresa_username_ci",
        "usuario",
        ["empresa_id", sa.literal_column("lower(username)")],
        unique=True,
    )
    op.create_index(
        "uq_usuario_plataforma_email_ci",
        "usuario",
        [sa.literal_column("lower(email)")],
        unique=True,
        postgresql_where=sa.text("empresa_id IS NULL"),
    )
    op.create_index(
        "uq_usuario_plataforma_username_ci",
        "usuario",
        [sa.literal_column("lower(username)")],
        unique=True,
        postgresql_where=sa.text("empresa_id IS NULL"),
    )
    op.create_table(
        "bitacora",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("usuario_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("actor_etiqueta", sa.String(length=150), nullable=True),
        sa.Column("modulo", sa.String(length=80), nullable=False),
        sa.Column("accion", sa.String(length=100), nullable=False),
        sa.Column("nivel", sa.String(length=16), server_default="INFO", nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("tabla_afectada", sa.String(length=100), nullable=True),
        sa.Column("registro_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("datos_previos_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("datos_nuevos_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_origen", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "fecha", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_bitacora_accion", "bitacora", ["accion"], unique=False)
    op.create_index("idx_bitacora_empresa_id", "bitacora", ["empresa_id"], unique=False)
    op.create_index("idx_bitacora_fecha", "bitacora", ["fecha"], unique=False)
    op.create_index("idx_bitacora_modulo", "bitacora", ["modulo"], unique=False)
    op.create_index("idx_bitacora_usuario_id", "bitacora", ["usuario_id"], unique=False)
    op.create_table(
        "email_verification_token",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("usuario_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "idx_email_verification_token_expires_at",
        "email_verification_token",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "idx_email_verification_token_usuario_id",
        "email_verification_token",
        ["usuario_id"],
        unique=False,
    )
    op.create_table(
        "password_reset_token",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("usuario_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_password_reset_token_empresa_id", "password_reset_token", ["empresa_id"], unique=False
    )
    op.create_index(
        "idx_password_reset_token_expires_at", "password_reset_token", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_password_reset_token_usuario_id", "password_reset_token", ["usuario_id"], unique=False
    )
    op.create_table(
        "refresh_token",
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("empresa_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("usuario_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_refresh_token_empresa_id", "refresh_token", ["empresa_id"], unique=False)
    op.create_index("idx_refresh_token_expires_at", "refresh_token", ["expires_at"], unique=False)
    op.create_index("idx_refresh_token_usuario_id", "refresh_token", ["usuario_id"], unique=False)
    op.create_table(
        "rol_permiso",
        sa.Column("rol_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("permiso_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["permiso_id"], ["permiso.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rol_id"], ["rol.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rol_id", "permiso_id"),
    )
    op.create_index("idx_rol_permiso_permiso_id", "rol_permiso", ["permiso_id"], unique=False)
    op.create_index("idx_rol_permiso_rol_id", "rol_permiso", ["rol_id"], unique=False)
    op.create_table(
        "usuario_rol",
        sa.Column("usuario_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("rol_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("asignado_por_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "fecha_asignacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asignado_por_id"], ["usuario.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rol_id"], ["rol.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("usuario_id", "rol_id"),
    )
    op.create_index("idx_usuario_rol_rol_id", "usuario_rol", ["rol_id"], unique=False)
    op.create_index("idx_usuario_rol_usuario_id", "usuario_rol", ["usuario_id"], unique=False)
    # ### end Alembic commands ###

    # ── Disparadores updated_at ──────────────────────────────────────────────
    # SQLAlchemy actualiza updated_at solo cuando el cambio pasa por el ORM. Estos
    # disparadores lo garantizan también para los UPDATE hechos en SQL directo
    # (migraciones de datos, correcciones manuales, scripts de mantenimiento).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$
        """
    )
    for tabla in (
        "empresa",
        "permiso",
        "rol",
        "usuario",
    ):
        op.execute(
            f"CREATE TRIGGER trg_{tabla}_updated_at BEFORE UPDATE ON {tabla} "
            f"FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()"
        )

    # ── Datos base ───────────────────────────────────────────────────────────
    permiso_table = sa.table(
        "permiso",
        sa.column("codigo", sa.String),
        sa.column("modulo", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("descripcion", sa.String),
    )
    op.bulk_insert(
        permiso_table,
        [
            {
                "codigo": codigo,
                "modulo": modulo,
                "recurso": recurso,
                "operacion": operacion,
                "descripcion": descripcion,
            }
            for codigo, modulo, recurso, operacion, descripcion in PERMISOS
        ],
    )

    # Rol global SUPER_ADMIN. No tiene acceso por una excepción en el código: se le
    # asignan explícitamente los permisos platform:*, igual que a cualquier otro rol.
    op.execute(
        "INSERT INTO rol (empresa_id, codigo, nombre, descripcion, es_base, activo) "
        "VALUES (NULL, 'SUPER_ADMIN', 'Super Administrador', "
        "'Administrador global de SSAS', true, true)"
    )
    op.execute(
        "INSERT INTO rol_permiso (rol_id, permiso_id) "
        "SELECT r.id, p.id FROM rol r CROSS JOIN permiso p "
        "WHERE r.empresa_id IS NULL AND r.codigo = 'SUPER_ADMIN' "
        "AND p.codigo LIKE 'platform:%'"
    )


def downgrade() -> None:
    """Elimina el esquema completo. Solo tiene sentido en una base descartable."""
    for tabla in (
        "bitacora",
        "email_verification_token",
        "password_reset_token",
        "refresh_token",
        "usuario_rol",
        "rol_permiso",
        "usuario",
        "rol",
        "permiso",
        "empresa",
    ):
        op.execute(f"DROP TABLE IF EXISTS {tabla} CASCADE")
    op.execute("DROP FUNCTION IF EXISTS public.set_updated_at() CASCADE")
