"""crear habilidades y vacantes

Revision ID: 7694bb109d4b
Revises: 20260830_0002
Create Date: 2026-08-30 15:24:29.644791

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7694bb109d4b'
down_revision: str | None = '20260830_0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilidad',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_habilidad_empresa_nombre')
    )
    op.create_index('idx_habilidad_empresa_id', 'habilidad', ['empresa_id'], unique=False)
    op.create_index('uq_habilidad_empresa_nombre_ci', 'habilidad', ['empresa_id', sa.literal_column('lower(nombre)')], unique=True)
    op.create_table('vacante',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cargo_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('departamento_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('responsable_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('requisitos', sa.Text(), nullable=True),
    sa.Column('beneficios', sa.Text(), nullable=True),
    sa.Column('cantidad_vacantes', sa.Integer(), server_default='1', nullable=False),
    sa.Column('salario_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salario_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mostrar_salario', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('ubicacion', sa.String(length=160), nullable=True),
    sa.Column('experiencia_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='BORRADOR', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('BORRADOR', 'PUBLICADA', 'PAUSADA', 'CERRADA', 'CANCELADA')", name='ck_vacante_estado'),
    sa.CheckConstraint("modalidad IN ('PRESENCIAL', 'REMOTO', 'HIBRIDO')", name='ck_vacante_modalidad'),
    sa.CheckConstraint('cantidad_vacantes > 0', name='ck_vacante_cantidad_positiva'),
    sa.CheckConstraint('experiencia_min >= 0', name='ck_vacante_experiencia_no_negativa'),
    sa.CheckConstraint('fecha_cierre IS NULL OR fecha_publicacion IS NULL OR fecha_cierre >= fecha_publicacion', name='ck_vacante_fechas'),
    sa.CheckConstraint('salario_max IS NULL OR salario_max >= 0', name='ck_vacante_salario_max_no_negativo'),
    sa.CheckConstraint('salario_min IS NULL OR salario_max IS NULL OR salario_max >= salario_min', name='ck_vacante_rango_salario'),
    sa.CheckConstraint('salario_min IS NULL OR salario_min >= 0', name='ck_vacante_salario_min_no_negativo'),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vacante_cargo_id', 'vacante', ['cargo_id'], unique=False)
    op.create_index('idx_vacante_departamento_id', 'vacante', ['departamento_id'], unique=False)
    op.create_index('idx_vacante_empresa_id', 'vacante', ['empresa_id'], unique=False)
    op.create_index('idx_vacante_estado', 'vacante', ['estado'], unique=False)
    op.create_index('idx_vacante_fecha_cierre', 'vacante', ['fecha_cierre'], unique=False)
    op.create_index('idx_vacante_responsable_id', 'vacante', ['responsable_id'], unique=False)
    op.create_table('vacante_habilidad',
    sa.Column('vacante_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('habilidad_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nivel_requerido', sa.String(length=30), nullable=False),
    sa.Column('es_obligatorio', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), server_default='1.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('peso > 0', name='ck_vacante_habilidad_peso_positivo'),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidad.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vacante_id', 'habilidad_id')
    )
    op.create_index('idx_vacante_habilidad_habilidad_id', 'vacante_habilidad', ['habilidad_id'], unique=False)
    for tabla in ("habilidad", "vacante", "vacante_habilidad"):
        op.execute(
            f"CREATE TRIGGER trg_{tabla}_updated_at BEFORE UPDATE ON {tabla} "
            "FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_vacante_habilidad_updated_at ON vacante_habilidad")
    op.execute("DROP TRIGGER IF EXISTS trg_vacante_updated_at ON vacante")
    op.execute("DROP TRIGGER IF EXISTS trg_habilidad_updated_at ON habilidad")
    op.drop_index('idx_vacante_habilidad_habilidad_id', table_name='vacante_habilidad')
    op.drop_table('vacante_habilidad')
    op.drop_index('idx_vacante_responsable_id', table_name='vacante')
    op.drop_index('idx_vacante_fecha_cierre', table_name='vacante')
    op.drop_index('idx_vacante_estado', table_name='vacante')
    op.drop_index('idx_vacante_empresa_id', table_name='vacante')
    op.drop_index('idx_vacante_departamento_id', table_name='vacante')
    op.drop_index('idx_vacante_cargo_id', table_name='vacante')
    op.drop_table('vacante')
    op.drop_index('uq_habilidad_empresa_nombre_ci', table_name='habilidad')
    op.drop_index('idx_habilidad_empresa_id', table_name='habilidad')
    op.drop_table('habilidad')
    # ### end Alembic commands ###
